### ISSUE TITLE
Don't have the .meta file

### ISSUE THREAD

**Issue by ghost** [r1cebank/tf-ckpt-2-pb#1]
@r1cebank Thank you for your hard work,
I want to convert a model provided by tensorflow :slim resnet v1 50.

It only contains the `resnet_v1_50.ckpt` file.

How can I convert the .ckpt file to .pb if I dont have the .meta file?

**Comment by r1cebank** [comment]
Hi @MrOCR 

For checkpoints, you can follow the guide here and restore the checkpoint first to the resnet model
https://www.tensorflow.org/guide/saved_model

Then later after the checkpoint is restored, you can the export it as a meta graph
https://www.tensorflow.org/api_guides/python/meta_graph

**Comment by ghost** [comment]
thanks
